-- Linguar Hub schema v10: durable editable job log.

create table if not exists crm_job_log_entries (
  entry_id           uuid primary key default gen_random_uuid(),
  job_id             uuid not null references jobs(job_id) on delete cascade,
  work_date          text not null,
  work_type          text not null,
  status             text not null check (status in
    ('scheduled','completed','rescheduled','cancelled','skipped','needs_review')),
  technicians        text,
  note               text,
  equipment          text,
  source             text not null default 'pc',
  source_id          text,
  trello_comment_id  text,
  created_at         text not null,
  updated_at         text not null,
  updated_by         text,
  unique (job_id, source, source_id)
);
create index if not exists idx_crm_job_log_job_date
  on crm_job_log_entries(job_id, work_date, created_at);

create table if not exists crm_job_log_revisions (
  revision_id  bigint generated by default as identity primary key,
  entry_id     uuid not null references crm_job_log_entries(entry_id)
                 on delete cascade,
  changed_at   text not null,
  changed_by   text,
  before_json  jsonb,
  after_json   jsonb not null
);
create index if not exists idx_crm_job_log_revisions_entry
  on crm_job_log_revisions(entry_id, revision_id);

alter table crm_job_log_entries enable row level security;
alter table crm_job_log_revisions enable row level security;

drop policy if exists crm_job_log_entries_rw on crm_job_log_entries;
create policy crm_job_log_entries_rw on crm_job_log_entries
  for all to authenticated
  using (exists (select 1 from jobs j where j.job_id = crm_job_log_entries.job_id))
  with check (exists (select 1 from jobs j where j.job_id = crm_job_log_entries.job_id));

drop policy if exists crm_job_log_revisions_rw on crm_job_log_revisions;
create policy crm_job_log_revisions_rw on crm_job_log_revisions
  for all to authenticated
  using (exists (
    select 1 from crm_job_log_entries e join jobs j on j.job_id=e.job_id
    where e.entry_id=crm_job_log_revisions.entry_id))
  with check (exists (
    select 1 from crm_job_log_entries e join jobs j on j.job_id=e.job_id
    where e.entry_id=crm_job_log_revisions.entry_id));

update meta set value='10' where key='schema_version';
insert into meta (key,value) values ('schema_version','10')
  on conflict (key) do update set value=excluded.value;
