const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const html=fs.readFileSync('analytics_web_assets/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
 await page.route('http://flow.test/**',r=>r.fulfill({contentType:'text/html',body:html}));await page.goto('http://flow.test');
 await page.addStyleTag({path:path.resolve('web_shared/theme.css')});
 await page.addStyleTag({path:path.resolve('web_shared/lane_timing_summary.css')});
 await page.addScriptTag({path:path.resolve('web_shared/lane_timing_summary.js')});
 for(const file of ['app.css','workspace_layout.css','flow.css','theme_controls.css','charts.css','navigation.css'])await page.addStyleTag({path:path.resolve('analytics_web_assets',file)});
 await page.evaluate(()=>{document.documentElement.dataset.theme='dark';window.messages=[];addEventListener('message',e=>messages.push(e.data));window.pywebview={api:{
 load_flow:async()=>{if(window.fail)return {ok:false,error:'Offline'};return {ok:true,location:'IE',source:'Test queues',lanes:['WORK IN PROGRESS','TBS NEW LOSS','TBS MITIGATION','TBS CONTENTS','TEST/CLEARANCE','PENDING APPROVALS','ON HOLD','SNAPSHOT','JUANTES','ZAC','KIM+ESTEBAN','AARON'].map((name,i)=>({id:String(i),board_id:i<7?'wip':'est',board:i<7?'WORK IN PROGRESS':'ESTIMATING',name,cards:[{id:'card'+i,name:'Sample job '+i}]}))};},
 flow_history:async()=>({ok:true,name:'Sample job',complete:true,current_seconds:null,periods:[],totals:[],estimator_cycles:[]})}};});
 for(const file of ['flow.js','app.js'])await page.addScriptTag({path:path.resolve('analytics_web_assets',file)});
 await page.evaluate(()=>dispatchEvent(new Event('pywebviewready')));await page.waitForSelector('[data-history]');
 assert.equal(await page.locator('#filters').isVisible(),false);
 assert.equal(await page.locator('.flow-color-key span').count(),3);
 assert.equal(await page.locator('.flow-bar-track').first().evaluate(el=>getComputedStyle(el).height),'20px');
 assert.equal(await page.locator('.flow-bar-track i').first().evaluate(el=>getComputedStyle(el).animationName),'chart-bar-enter');
 assert.equal(await page.locator('.flow-column-track i').first().evaluate(el=>getComputedStyle(el).animationName),'chart-column-enter');
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('.flow-bar-track i').first().evaluate(el=>getComputedStyle(el).animationName),'none');
 await page.emulateMedia({reducedMotion:'no-preference'});
 assert.equal(await page.locator('[data-chart-board="wip"] strong').textContent(),'7');
 assert.equal(await page.locator('[data-chart-board="est"] strong').textContent(),'5');
 assert.equal(await page.locator('[data-chart-board="wip"] i').evaluate(el=>el.style.height),'100%');
 await page.locator('[data-chart-board="est"]').click();assert.equal(await page.locator('[data-history]').count(),5);
 assert.equal(await page.locator('.flow-bar-track i').first().evaluate(el=>getComputedStyle(el).animationName),'none','Filtering must not replay entrance');
 await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='Test queues');
 assert.equal(await page.locator('.flow-chart-enter').count(),0,'Refresh must not replay entrance');
 await page.locator('#flow-board').selectOption('');
 await page.locator('[data-lane="6"]').click();assert.equal(await page.locator('[data-history]').count(),1);
 await page.locator('[data-flow-open]').click();await page.waitForFunction(()=>messages.some(m=>m.cardId==='card6'));
 await page.locator('[data-history]').click();await page.waitForSelector('#flow-history h3');
 assert.match(await page.locator('#flow-history').textContent(),/Unknown/);
 assert.match(await page.locator('.timing-coverage').textContent(),/does not prove/);
 assert.match(await page.locator('.lane-time-summary').textContent(),/Snapshot turnaround/);
 await page.keyboard.press('Escape');assert.equal(await page.locator('#flow-history').isVisible(),false);
 await page.evaluate(()=>{pywebview.api.flow_history=async()=>({ok:true,name:'Sample job — timing review',complete:true,current_seconds:527400,estimator_cycles:[{first_lane:'JOHNNY',started:'2026-10-01T17:20:00Z',ended:null,seconds:527400},{first_lane:'ZAC',started:'2026-09-01T17:20:00Z',ended:'2026-09-03T17:20:00Z',seconds:172800}],totals:[{board:'ESTIMATING',lane:'SNAPSHOT',seconds:62000,visits:1}],periods:[{board:'ESTIMATING',lane:'SNAPSHOT',entered:'2026-09-30T17:20:00Z',exited:'2026-10-01T17:20:00Z',seconds:86400,actor:'Sample coordinator'},{board:'ESTIMATING',lane:'JOHNNY',entered:'2026-10-01T17:20:00Z',exited:null,current:true,seconds:527400,actor:'Sample estimator'}]});});
 await page.locator('[data-history]').click();await page.waitForSelector('.timing-cycle');
 assert.equal(await page.locator('.timing-cycle').count(),2);
 assert.match(await page.locator('.timing-current').textContent(),/6d 2h/);
 assert.match(await page.locator('.timing-cycle').last().textContent(),/Reached Logs/);
 await page.screenshot({path:path.join(os.tmpdir(),'oneloss-timing-detail.png'),animations:'disabled'});
 await page.setViewportSize({width:390,height:844});
 assert(await page.locator('#flow-history').evaluate(el=>el.scrollWidth<=el.clientWidth));
 await page.screenshot({path:path.join(os.tmpdir(),'oneloss-timing-detail-mobile.png')});
 await page.keyboard.press('Escape');await page.setViewportSize({width:1280,height:900});
 await page.locator('#flow-all').click();await page.locator('#flow-search').fill('Sample job 2');assert.equal(await page.locator('[data-history]').count(),1);
 await page.locator('#flow-search').fill('');
 assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(23, 25, 28)');
 assert.equal(await page.locator('.flow-chart').first().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(32, 35, 40)');
 await page.screenshot({path:path.join(os.tmpdir(),'oneloss-analytics-flow.png'),fullPage:true});
 await page.evaluate(()=>document.documentElement.dataset.theme='light');
 assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(245, 247, 244)');
 assert.equal(await page.locator('.flow-chart').first().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');
 await page.evaluate(()=>document.documentElement.dataset.theme='dark');
 await page.evaluate(()=>window.fail=true);await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Offline'));
 assert.equal(await page.locator('[data-history]').count(),12);
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-history]').first().click();assert.equal(await page.locator('#flow-history').evaluate(el=>getComputedStyle(el).animationName),'none');
 assert.deepEqual(errors,[]);console.log('PASS: queues, filters, exact card, unknown timing, failed refresh retains content, narrow layout, reduced motion');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
