const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const html=fs.readFileSync('notifications_web_assets/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'');await page.setContent(html);
 for(const f of ['web_shared/theme.css','notifications_web_assets/personal.css','notifications_web_assets/inbox.css','web_shared/comment_display.css'])await page.addStyleTag({path:path.resolve(f)});
 await page.evaluate(()=>{
  document.documentElement.dataset.theme='dark';window.calls=[];window.failed=false;window.posts=[];window.addEventListener('message',e=>posts.push(e.data));
  window.PanelState={init:async()=>{},get:(k,v)=>v,set:()=>{}};
  window.pywebview={api:{personal_inbox:async()=>({ok:true,items:[]}),list_notifications:async()=>({ok:true,total:1,unread:1,groups:[{board:'Work in progress',unread:1,total:1,items:[{id:'n1',card_id:'a'.repeat(24),comment_id:'b'.repeat(24),card_name:'Example restoration job',snippet:'**Inspection ready**\n\n@nathan Please review [the report](https://example.com).\n\n'+('Long message. '.repeat(100)),by:'Sam',unread:true,type_label:'Mention',icon:'💬',card_url:'https://trello.com/c/abcd1234'}]}]}),notification_job:async(...a)=>{calls.push(a);return failed?{ok:false,error:'No verified job link.'}:{ok:true,client:'Example restoration job',cardId:a[0],commentId:a[1],division:'Contents'};},mark_read:async()=>({ok:true}),open_url:async url=>calls.push(['url',url])}};
 });
 for(const f of ['web_shared/vendor/markdown-it/markdown-it.min.js','pipeline_web_assets/comment_markdown.js','notifications_web_assets/reader.js','notifications_web_assets/app.js','notifications_web_assets/personal.js'])await page.addScriptTag({path:path.resolve(f)});
 await page.evaluate(()=>dispatchEvent(new Event('pywebviewready')));await page.locator('#trello-source').click();await page.locator('.notif').waitFor();
 assert(await page.locator('.notif-snippet').evaluate(e=>e.clientHeight<60));assert.equal(await page.locator('.notif-snippet strong').innerText(),'Inspection ready');
 await page.getByRole('button',{name:'Read message',exact:true}).click();await page.locator('#notification-reader').waitFor();assert(await page.locator('#notification-reader').innerText().then(t=>t.includes('Long message.')));
 await page.waitForTimeout(200);await page.screenshot({path:path.join(process.env.TEMP,'oneloss-inbox-reader.png')});await page.keyboard.press('Escape');await page.locator('#notification-reader').waitFor({state:'detached'});
 await page.locator('[data-open-notification]').click();await page.waitForFunction(()=>posts.some(p=>p.type==='linguar-open-job'));assert.equal(await page.evaluate(()=>posts.find(p=>p.type==='linguar-open-job').commentId),'b'.repeat(24));
 await page.evaluate(()=>failed=true);await page.locator('[data-open-notification]').click();await page.locator('#notification-reader').waitFor();assert.match(await page.locator('#notification-reader [role=status]').innerText(),/verified/);await page.getByRole('button',{name:'Open in Trello',exact:true}).click();assert((await page.evaluate(()=>calls)).some(c=>c[0]==='url'&&c[1].endsWith('#comment-'+'b'.repeat(24))));
 await page.setViewportSize({width:420,height:780});assert(await page.locator('#notification-reader').evaluate(e=>e.getBoundingClientRect().right<=innerWidth));
 await page.keyboard.press('Escape');await page.locator('#notification-reader').waitFor({state:'detached'});await page.screenshot({path:path.join(process.env.TEMP,'oneloss-inbox-compact.png')});
 await page.setContent('<button class="sb-item" data-key="notifications">Notifications</button><textarea>Unsent draft stays here</textarea>');await page.evaluate(()=>{window.calls=[];pywebview.api.open_popout=async(...a)=>{calls.push(a);return {ok:true};};});
 await page.addScriptTag({path:path.resolve('web_shared/popout_menu.js')});await page.locator('.sb-item').click({button:'right'});await page.getByRole('menuitem',{name:'Open in new window'}).click();assert.equal(await page.locator('textarea').inputValue(),'Unsent draft stays here');assert.equal(await page.evaluate(()=>calls[0][0]),'notifications');
 await page.setContent('<section id="workspace"><div data-comment-stream><article data-comment-id="bbbbbbbbbbbbbbbbbbbbbbbb" data-comment-card-id="aaaaaaaaaaaaaaaaaaaaaaaa">Exact comment</article></div></section>');await page.addScriptTag({path:path.resolve('pipeline_web_assets/notification_focus.js')});await page.evaluate(()=>focusNotificationComment({element:document.querySelector('#workspace')},'a'.repeat(24),'b'.repeat(24)));assert.equal(await page.locator('.notification-comment-target').count(),1);
 assert.deepEqual(errors,[]);console.log('PASS: compact Markdown previews, reading pane, exact comment route, missing-link fallback, narrow view, right-click popout and highlight');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
