const {chromium}=require('playwright');
const path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:950}});
  await page.setContent('<div id="status-msg"></div>');
  await page.addScriptTag({path:path.resolve('web_shared/job_activities.js')});
  for(const f of ['web_shared/theme.css','pipeline_web_assets/app.css','pipeline_web_assets/job_workspace_tabs.css'])await page.addStyleTag({path:path.resolve(f)});
  for(const f of ['web_shared/modal.js','pipeline_web_assets/job_workspace_tabs.js','pipeline_web_assets/job_conversation.js','pipeline_web_assets/app.js'])await page.addScriptTag({path:path.resolve(f)});
  await page.evaluate(()=>{
   document.documentElement.dataset.theme='dark';
   window.saved=[];
   window.pywebview={api:{save_job_log_update:async(c,p)=>{saved.push(p);return {ok:true,entry:{...p,entry_id:p.entry_id||'new'}};}}};
   openAuditModal({ok:true,client:'Sub test',card_id:'card',selected_division:'EMS',audit:{found:true},comments:[],crm:{job_log:[
    {entry_id:'old',work_date:'2026-09-27',work_type:'Monitor'},
    {entry_id:'crew',work_date:'2026-09-28',work_type:'Demo',work_party:'crew'},
    {entry_id:'sub',work_date:'2026-09-29',work_type:'Testing',work_party:'subcontractor',subcontractor:'Titan',technicians:'Sam'}]}});
  });
  await page.locator('#job-tab-log').click();
  const visible=()=>page.locator('[data-job-log-id]:visible').count();
  assert.equal(await visible(),3);
  await page.locator('[data-log-party-filter]').selectOption('subcontractor');
  assert.equal(await visible(),1);
  assert.match(await page.locator('[data-job-log-id="sub"]').textContent(),/Sub · Titan/);
  await page.locator('[data-log-company-filter]').selectOption('Titan');
  await page.locator('[data-edit-job-log="sub"]').click();
  assert.equal(await page.locator('[data-job-log-id="sub"] [data-job-log-editor]').count(),1,'Edit replaces the selected row in place');
  assert.equal(await page.locator('[data-log-party-filter]').isDisabled(),true);
  await page.locator('[data-job-log-id="sub"]').screenshot({path:path.join(require('os').tmpdir(),'oneloss-inline-log-edit.png')});
  assert.equal(await page.locator('[data-log-field="subcontractor"]').inputValue(),'Titan');
  await page.locator('[data-log-field="note"]').fill('Testing completed');
  const beforePicker = await page.getByRole('textbox',{name:'Testing assigned to',exact:true}).boundingBox();
  await page.getByLabel('Select activities').click();
  await page.waitForSelector('.job-activity-options:popover-open');
  const afterPicker = await page.getByRole('textbox',{name:'Testing assigned to',exact:true}).boundingBox();
  assert.equal(afterPicker.y,beforePicker.y,'Picker must not stretch the form');
  assert.equal(await page.locator('.job-activity-options input[type=checkbox]').count(),0);
  await page.locator('.job-activity-options').getByRole('button',{name:'Demo',exact:true}).click();
  await page.locator('.job-activity-options').getByRole('button',{name:'Monitor',exact:true}).click();
  assert.equal(await page.locator('.job-activity-options').getByRole('button',{name:'Demo',exact:true}).getAttribute('aria-pressed'),'true');
  await page.screenshot({path:path.join(require('os').tmpdir(),'oneloss-activity-popover.png')});
  await page.getByLabel('Select activities').press('Escape');
  await page.getByRole('textbox',{name:'Demo assigned to',exact:true}).fill('ME');
  await page.getByRole('textbox',{name:'Monitor assigned to',exact:true}).fill('FB');
  await page.locator('[data-save-job-log]').click();
  assert.equal(await page.evaluate(()=>saved[0].work_type),'Testing + Demo + Monitor');
  assert.equal(await page.evaluate(()=>saved[0].technicians),'Testing: Sam | Demo: ME | Monitor: FB');
  assert.equal(await page.locator('[data-log-party-filter]').inputValue(),'subcontractor');
  assert.equal(await visible(),1);
  assert.equal(await page.locator('[data-job-log-id="sub"] [data-job-log-editor]').count(),0,'Save restores normal row');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.locator('[data-edit-job-log="sub"]').click();
  assert.equal(await page.getByRole('textbox',{name:'Demo assigned to',exact:true}).inputValue(),'ME');
  assert.equal(await page.getByRole('textbox',{name:'Monitor assigned to',exact:true}).inputValue(),'FB');
  await page.locator('[data-job-log-id="sub"]').screenshot({path:path.join(require('os').tmpdir(),'oneloss-multiple-activities.png')});
  assert.equal(await page.locator('[data-job-log-id="sub"]').evaluate(el=>el.getAnimations().length),0);
  await page.locator('[data-log-field="note"]').fill('Discard this draft');
  await page.locator('[data-cancel-job-log]').click();
  assert.equal(await page.locator('[data-job-log-editor]:visible').count(),0);
  assert.match(await page.locator('[data-job-log-id="sub"]').textContent(),/Testing completed/);
  assert.equal(await page.locator('[data-log-party-filter]').isDisabled(),false);
  await page.locator('[data-log-party-filter]').selectOption('crew');
  assert.equal(await visible(),1);
  await page.locator('[data-log-party-filter]').selectOption('');
  assert.equal(await visible(),1);
  await page.locator('[data-log-party-filter]').selectOption('all');
  await page.locator('.job-log-section [data-add-job-log]').click();
  await page.locator('[data-log-field="work_party"]').selectOption('subcontractor');
  await page.locator('[data-save-job-log]').click();
  assert.equal(await page.evaluate(()=>saved.length),1,'Blank company cannot save');
  await page.locator('[data-log-field="subcontractor"]').fill('Second company');
  await page.getByLabel('Select activities').click();
  await page.getByRole('textbox',{name:'Custom activity',exact:true}).fill('Clearance visit');
  await page.locator('.job-activity-options').getByRole('button',{name:'Add activity',exact:true}).click();
  assert.equal(await page.locator('.job-activity-options').getByRole('button',{name:'Clearance visit',exact:true}).getAttribute('aria-pressed'),'true');
  await page.getByRole('textbox',{name:'Clearance visit assigned to',exact:true}).fill('RQ');
  assert.equal(await page.locator('.job-activity-options:popover-open').count(),0,'Leaving picker dismisses overlay');
  await page.locator('[data-log-post-trello]').uncheck();
  await page.locator('[data-save-job-log]').click();
  assert.equal(await visible(),4);
  assert.equal(await page.evaluate(()=>saved[1].subcontractor),'Second company');
  assert.match(await page.evaluate(()=>saved[1].work_type),/Clearance visit/);
  assert.match(await page.evaluate(()=>saved[1].technicians),/Clearance visit: RQ/);
  await page.locator('.job-log-section').screenshot({path:path.join(require('os').tmpdir(),'oneloss-sub-log.png')});
  await page.setViewportSize({width:960,height:800});
  assert.ok(await page.locator('[data-log-filters]').evaluate(n=>n.scrollWidth<=n.clientWidth+1));
  console.log('Subcontractor Job Log: PASS');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
