const {chromium}=require('playwright'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1400,height:900}});
 await page.goto('file:///'+path.resolve('pipeline_web_assets/index.html').replace(/\\/g,'/'));
 await page.evaluate(async()=>{
  window.saved={};window.opened=[];window.pywebview={api:{get_ui_state:async key=>saved[key]||{},set_ui_state:async(key,value)=>{saved[key]=value;return {ok:true}}}};
  const card=(id,carrier)=>({card_id:id,client:'Example '+id,url:'',list_id:'lane',job_info:{carrier},loss_types:['Water'],checklist:{done:2,total:5},stall:'none'});
  state.board={boards:[{key:'wip',name:'WORK IN PROGRESS',board_id:'wip',lanes:[{name:'Monitoring',list_id:'lane',cards:[card('a','State Farm'),card('b','AAA')]}]},{key:'est',name:'ESTIMATING',board_id:'est',lanes:[{name:'Needs estimate',list_id:'estimate',cards:[{...card('c','State Farm'),list_id:'estimate'}]}]}]};
  await JobViews.init('user-one',{redraw:()=>renderBoardContent(),choose:key=>{state.activeBoardKey=key;state.search='';state.boardFilter='all'},search:()=>state.search,renderCard,open:c=>opened.push(c.card_id)});
  renderBoardContent();
 });
 assert.equal(await page.locator('.lane').count(),1);
 assert.equal(await page.locator('#job-views-trial').count(),0);
 await page.locator('[data-saved="all"]').click();assert.equal(await page.locator('[data-result]').count(),3);
 assert.equal(await page.locator('.kcard').count(),0);
 assert.equal(await page.locator('.all-jobs-list thead th').count(),8);
 assert.equal(await page.locator('[data-plan], [data-phase-info], [data-field=progress]').count(),0);
 assert.equal(await page.locator('[data-field=board]').first().textContent(),'WORK IN PROGRESS');
 assert.equal(await page.locator('[data-field=lane]').first().textContent(),'Monitoring');
 assert.equal(await page.locator('[data-field=checklist] progress').first().getAttribute('value'),'2');
 await page.locator('[data-config=density]').selectOption('comfortable');
 assert.equal(await page.locator('.jobs-list-prototype').getAttribute('data-density'),'comfortable');
 await page.locator('[data-config=density]').selectOption('compact');
 await page.locator('.jobs-columns summary').click();await page.locator('[data-reorder=lane][data-step="-1"]').click();
 assert.equal(await page.locator('.all-jobs-list thead th').nth(1).textContent(),'Lane');
 await page.locator('[data-reset-columns]').click();
 await page.locator('.all-jobs-open').first().focus();await page.keyboard.press('Enter');assert.deepEqual(await page.evaluate(()=>opened),['a']);
 await page.screenshot({path:path.join(process.env.TEMP,'oneloss-all-jobs-list.png')});
 const originalBoard=await page.evaluate(()=>JSON.stringify(state.board));
 await page.locator('[data-config=group]').selectOption('carrier');
 assert.equal(await page.locator('[data-group]').count(),2);
 await page.locator('[data-group]').first().click();assert.equal(await page.locator('[data-result]').count(),1);
 await page.locator('[data-group]').first().click();assert.equal(await page.locator('[data-result]').count(),3);
 await page.locator('[data-config=group]').selectOption('');
 await page.locator('[data-config=direction]').selectOption('desc');
 assert.equal(await page.locator('.all-jobs-open').first().textContent(),'Example c');
 await page.locator('[data-config=direction]').selectOption('asc');
 await page.locator('.jobs-columns summary').click();await page.locator('[data-column=address]').check();
 assert.equal(await page.locator('.all-jobs-list thead th').count(),9);
 await page.locator('.jobs-columns summary').click();
 assert.equal(await page.evaluate(()=>JSON.stringify(state.board)),originalBoard);
 await page.screenshot({path:path.join(process.env.TEMP,'oneloss-real-tracking.png')});
 await page.locator('[data-create-view]').click();await page.locator('[name=name]').fill('State Farm');await page.locator('[name=carrier]').selectOption('State Farm');await page.getByRole('button',{name:'Save my view',exact:true}).click();
 assert.equal(await page.locator('[data-result]').count(),2);
 assert.equal(await page.locator('.all-jobs-list thead th').count(),9);
 await page.locator('[data-edit-view]').click();await page.locator('[name=board]').selectOption('wip');await page.locator('[name=layout]').selectOption('board');await page.getByRole('button',{name:'Save my view',exact:true}).click();
 assert.equal(await page.locator('.lane').count(),1);assert.equal(await page.locator('.kcard').count(),1);
 await page.screenshot({path:path.join(process.env.TEMP,'oneloss-inline-views.png')});
 await page.locator('[data-delete-view]').click();await page.getByRole('button',{name:'Delete my view',exact:true}).click();assert.equal(await page.locator('[data-result]').count(),3);
 await page.evaluate(()=>{state.search='no matches';renderBoardContent()});assert.equal(await page.locator('[data-result]').count(),0);assert(await page.locator('.all-jobs-empty').isVisible());
 await page.evaluate(()=>{state.search='';const lane=state.board.boards[0].lanes[0];window.originalCards=lane.cards;lane.cards=Array.from({length:350},(_,i)=>({...originalCards[0],card_id:'bulk'+i,client:'Job '+i}));renderBoardContent()});
 assert.equal(await page.locator('[data-result]').count(),351);
 await page.setViewportSize({width:700,height:800});assert(await page.evaluate(()=>{const list=document.querySelector('.all-jobs-list');return list.scrollWidth>list.clientWidth}));
 await page.evaluate(()=>{document.querySelector('.all-jobs-list').scrollLeft=400;document.querySelector('.all-jobs-list').scrollTop=200});
 assert(await page.evaluate(()=>{const list=document.querySelector('.all-jobs-list'),cell=list.querySelector('[data-field=job]'),head=list.querySelector('thead th');return Math.abs(cell.getBoundingClientRect().left-list.getBoundingClientRect().left)<2&&Math.abs(head.getBoundingClientRect().top-list.getBoundingClientRect().top)<2}));
 await page.evaluate(()=>{state.board.boards[0].lanes[0].cards=originalCards;renderBoardContent()});
 assert.equal(await page.evaluate(()=>state.board.boards[0].lanes[0].cards.length),2);
 await page.locator('[data-main="wip"]').click();assert.equal(await page.locator('.kcard').count(),2);
 assert(await page.evaluate(()=>Object.keys(saved).every(k=>k==='dev-job-views:user-one')));
 console.log('PASS: existing lanes retained, all records, exact popup target, personal filters, edit/delete without job mutation, scoped save.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
