// Isolated PostgreSQL only; exercises the real placement lifecycle and outbox.
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
(async()=>{
 const db=new PGlite(),user=randomUUID(),job=randomUUID(),job2=randomUUID(),visit=randomUUID(),visit2=randomUUID();
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
 create table auth.users(id uuid primary key);insert into auth.users values('${user}');
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create table app_user_departments(user_id uuid,department text);insert into app_user_departments values('${user}','IE');
 create function public.my_departments() returns setof text language sql as $$select department from public.app_user_departments where user_id=auth.uid()$$;
 create function public.is_app_admin() returns boolean language sql as $$select false$$;
 create table jobs(job_id uuid primary key,department text,canon_key text);
 insert into jobs values('${job}','IE','job'),('${job2}','IE','job2');
 create table job_links(canon_key text,link_type text,link_value text);
 insert into job_links values('job','trello_card','aaaaaaaaaaaaaaaaaaaaaaaa'),('job2','trello_card','bbbbbbbbbbbbbbbbbbbbbbbb');
 create table hub_trello_sync_sources(board_id text,label text,reader_workspace text,reader_department text,required_departments text[],lists_json jsonb,enabled boolean);
 create table hub_trello_mirror_cards(card_id text primary key,board_id text,payload jsonb,present boolean);
 grant usage on schema auth to authenticated;
 grant select on jobs,app_user_departments,job_links,hub_trello_mirror_cards to authenticated;`);
 for(const name of ['20260923175120_app_card_placement_lifecycle.sql','20260923180531_app_placement_scope_guards.sql','20261005150008_oneloss_schedule_drafts.sql','20261005154121_schedule_bulk_import.sql','20261005215806_schedule_day_confirmation.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
 await db.exec(`insert into app_job_boards values('wip','WORK IN PROGRESS','office','IE',array['IE'],'[{"id":"old","name":"TBS"},{"id":"work","name":"WORK IN PROGRESS"},{"id":"recon","name":"RECONSTRUCTION"}]',true);
 insert into hub_trello_mirror_cards values('aaaaaaaaaaaaaaaaaaaaaaaa','wip','{"idList":"old","name":"A"}',true),('bbbbbbbbbbbbbbbbbbbbbbbb','wip','{"idList":"old","name":"B"}',true);
 set role authenticated;select set_config('test.uid','${user}',false);`);
 const payload=(id,jid)=>({id,job_id:jid,queue:'scheduled',group:'Work To Be Performed',date:'2026-10-05',arrival:'',activities:[{label:'Demo',people:[]}],equipment:'',access:'',notes:'',status:'active'});
 const save=async(v,revision=0)=>(await db.query('select save_schedule_entry($1::jsonb) r',[JSON.stringify({contract_version:2,department:'IE',operation_id:randomUUID(),expected_revision:revision,entry_title:'',source_key:null,visit:v})])).rows[0].r;
 await save(payload(visit,job));await save(payload(visit2,job2));
 const entry=(id,card)=>({id,revision:1,action:'move',card_id:card,board_id:'wip',from_list:'old',list_id:'work',version:0});
 const base={contract_version:1,department:'IE',date:'2026-10-05',entries:[entry(visit,'aaaaaaaaaaaaaaaaaaaaaaaa'),entry(visit2,'bbbbbbbbbbbbbbbbbbbbbbbb')]};
 const confirm=async(c)=>(await db.query('select confirm_schedule_day($1::jsonb) r',[JSON.stringify(c)])).rows[0].r;
 const command=()=>({...structuredClone(base),operation_id:randomUUID()});
 let c=command();c.entries[1].revision=99;
 await assert.rejects(confirm(c),/Day changed/);
 assert.equal((await db.query('select * from app_card_placements')).rows.length,0,'All board moves roll back');
 assert.equal((await db.query('select * from schedule_confirmations')).rows.length,0);
 c=command();c.entries.pop();await assert.rejects(confirm(c),/Day changed/);
 c=command();c.entries[0].list_id='recon';await assert.rejects(confirm(c),/non-Recon/);
 c=command();c.entries[0].card_id='bbbbbbbbbbbbbbbbbbbbbbbb';c.entries[1].action='keep';await assert.rejects(confirm(c),/link needs review/);
 c=command();c.entries[0].from_list='changed';await assert.rejects(confirm(c),/Card changed/);
 // A user must not bypass catalog RLS by using the definer endpoint.
 await db.exec("reset role;update app_job_boards set required_departments=array['IE','OTHER'];set role authenticated;");
 await assert.rejects(confirm(command()),/accessible WIP/);
 await db.exec("reset role;update app_job_boards set required_departments=array['IE'],name='RECON WORK IN PROGRESS';set role authenticated;");
 await assert.rejects(confirm(command()),/accessible WIP/);
 await db.exec("reset role;update app_job_boards set name='WORK IN PROGRESS';set role authenticated;");
 c=command();const result=await confirm(c);assert.equal(result.confirmed,2);assert.equal(result.moved,2);
 assert.deepEqual(await confirm(c),result,'Identical response after retry');
 assert.equal((await db.query('select * from schedule_confirmations')).rows.length,1);
 assert.equal((await db.query('select snapshot from schedule_confirmations')).rows[0].snapshot[0].placement.card_json,undefined);
 let rows=(await db.query('select * from app_card_placements')).rows;
 assert.ok(rows.every(r=>r.version===1&&r.synced_version===0&&r.list_id==='work'&&r.events[0].actor===user));
 await assert.rejects(confirm({...c,date:'2026-10-06'}),/Operation ID reused/);
 assert.ok((await db.query('select * from schedule_visits')).rows.every(r=>Number(r.confirmed_revision)===1));
 await save({...payload(visit,job),arrival:'10 AM'},1);
 const changed=(await db.query('select * from schedule_visits where id=$1',[visit])).rows[0];
 assert.equal(Number(changed.confirmed_revision),1);assert.equal(Number(changed.revision),2,'New edit is draft again');
 await assert.rejects(confirm(command()),/changed/);
 const keep=command();keep.entries=keep.entries.map((e,i)=>({id:e.id,revision:i?1:2,action:'keep'}));
 assert.equal((await confirm(keep)).moved,0);
 assert.equal((await db.query('select * from app_card_placements')).rows[0].version,1,'Keep does not move');
 const noVisits={...keep,operation_id:randomUUID(),date:'2026-10-06',entries:[]};
 await assert.rejects(confirm(noVisits),/Invalid day confirmation/);
 await assert.rejects(db.exec('delete from schedule_confirmations'),/permission denied/);
 await assert.rejects(db.exec('update schedule_visits set confirmed_revision=revision'),/permission denied/);
 await db.exec(`select set_config('test.uid','${randomUUID()}',false)`);
 assert.equal((await db.query('select * from schedule_confirmations')).rows.length,0);
 await assert.rejects(confirm(keep),/Office access/);
 await db.exec('set role anon');await assert.rejects(confirm(keep),/permission denied/);
 await db.close();console.log('Confirmation: atomic board moves, retries, stale day, links, Recon, permissions and re-draft passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
