// Isolated PostgreSQL tests. Never connects to the live project.
const {PGlite}=require(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const db=new PGlite();
 const user='10000000-0000-4000-8000-000000000001',job='20000000-0000-4000-8000-000000000001';
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key); insert into auth.users values('${user}');
 create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
 create table public.app_user_departments(user_id uuid,department text);
 insert into public.app_user_departments values('${user}','IE');
 create table public.jobs(job_id uuid primary key,department text);
 insert into public.jobs values('${job}','IE'),('20000000-0000-4000-8000-000000000002','OTHER'),('20000000-0000-4000-8000-000000000003','IE');
 create function public.my_departments() returns setof text language sql as $$ select department from public.app_user_departments where user_id=auth.uid() $$;
 grant usage on schema auth to authenticated; grant select on jobs,app_user_departments to authenticated;`);
 await db.exec(fs.readFileSync('supabase/migrations/20261005150008_oneloss_schedule_drafts.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20261005154121_schedule_bulk_import.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20261005171816_run_document_history.sql','utf8'));
 await db.exec(`set role authenticated; select set_config('test.uid','${user}',false);`);
 const visit={id:'30000000-0000-4000-8000-000000000001',job_id:job,queue:'scheduled',group:'Work To Be Performed',date:'2026-10-05',arrival:'',activities:[{label:'Demo',people:['Sam']}],equipment:'',access:'',notes:'',status:'active'};
 let n=0; const command=(v=visit,rev=0)=>({contract_version:1,department:'IE',operation_id:`40000000-0000-4000-8000-${String(++n).padStart(12,'0')}`,expected_revision:rev,visit:v});
 const save=async c=>(await db.query('select public.save_schedule_draft($1::jsonb) as result',[JSON.stringify(c)])).rows[0].result;
 const first=command(),saved=await save(first);
 assert.equal(saved.revision,1);assert.deepEqual(await save(first),saved);
 assert.equal((await db.query('select * from schedule_changes')).rows.length,1);
 await assert.rejects(save({...first,visit:{...visit,notes:'different'}}),/Operation ID reused/);
 await assert.rejects(save(command()),/changed elsewhere/);
 assert.equal((await save(command({...visit,notes:'next'},1))).revision,2);
 await assert.rejects(save(command({...visit,id:'30000000-0000-4000-8000-000000000002'})),/schedule_one_active_job/);
 await assert.rejects(save(command({...visit,job_id:'20000000-0000-4000-8000-000000000002'},2)),/unavailable/);
 await assert.rejects(save(command({...visit,date:'2026-02-30'},2)),/Invalid visit/);
 await assert.rejects(save(command({...visit,claim_number:'bad'},2)),/Invalid visit/);
 await assert.rejects(save(command({...visit,activities:[]},2)),/Invalid visit/);
 await assert.rejects(save(command({...visit,activities:[{label:'Demo',people:['Sam','sam']}]},2)),/Invalid visit/);
 const other={...visit,id:'30000000-0000-4000-8000-000000000003',job_id:'20000000-0000-4000-8000-000000000003'};
 const reordered=await save({...command(other),before_id:visit.id});
 assert.ok(Number(reordered.position)<Number(saved.position));
 await assert.rejects(save({...command({...other,date:'2026-10-06'},1),before_id:visit.id}),/Drop destination changed/);
 const moved=await save(command({...other,queue:'tbs',group:'TBS Mitigation',date:null},1));
 assert.equal(moved.payload.date,null);
 await assert.rejects(db.exec('delete from schedule_visits'),/permission denied/);
 await assert.rejects(db.exec('delete from schedule_changes'),/permission denied/);
 await save(command({...visit,status:'canceled'},2));
 await save(command({...visit,id:'30000000-0000-4000-8000-000000000002'}));
 const unlinked={...command({...visit,id:'30000000-0000-4000-8000-000000000004',job_id:null}),contract_version:2,entry_title:'Unmatched home',source_key:'source-row-1'};
 const saveEntry=async c=>(await db.query('select public.save_schedule_entry($1::jsonb) as result',[JSON.stringify(c)])).rows[0].result;
 const bulk=async entries=>(await db.query('select public.import_schedule_entries($1,$2::jsonb) as result',['IE',JSON.stringify(entries)])).rows[0].result;
 assert.equal((await bulk([unlinked])).added,1);
 assert.equal((await bulk([unlinked])).already_imported,1);
 const changed={...unlinked,operation_id:command().operation_id,expected_revision:1,entry_title:'Edited unmatched'};
 assert.equal((await saveEntry(changed)).revision,2);
 assert.equal((await bulk([unlinked])).already_imported,1);
 await assert.rejects(saveEntry({...changed,operation_id:command().operation_id,expected_revision:2,visit:{...unlinked.visit,job_id:'20000000-0000-4000-8000-000000000002'}}),/unavailable/);
 const collision={...unlinked,operation_id:command().operation_id,source_key:'source-row-2',visit:{...visit,id:'30000000-0000-4000-8000-000000000005'}};
 assert.equal((await bulk([collision])).needs_link,1);
 await assert.rejects(saveEntry({...changed,operation_id:command().operation_id}),/changed elsewhere/);
 const rollback={...unlinked,operation_id:command().operation_id,source_key:'rollback',visit:{...unlinked.visit,id:'30000000-0000-4000-8000-000000000006'}};
 await assert.rejects(bulk([rollback,{...rollback,department:'OTHER'}]),/Invalid import/);
 assert.equal((await db.query("select count(*)::int as n from schedule_visits where source_key='rollback'")).rows[0].n,0);
 await save(command({...other,status:'canceled'},2));
 const linked=await saveEntry({...changed,operation_id:command().operation_id,expected_revision:2,visit:{...unlinked.visit,job_id:other.job_id}});
 assert.equal(linked.job_id,other.job_id);
 assert.equal(linked.id,unlinked.visit.id);
 assert.equal((await saveEntry({...changed,operation_id:command().operation_id,expected_revision:3})).job_id,null);
 await db.exec("select set_config('test.uid','10000000-0000-4000-8000-000000000099',false)");
 assert.equal((await db.query('select * from schedule_visits')).rows.length,0);
 assert.equal((await db.query('select * from schedule_changes')).rows.length,0);
 await assert.rejects(save(command()),/unavailable/);
 await db.exec('set role anon');
 await assert.rejects(save(command()),/permission denied/);
 await db.exec(`set role authenticated; select set_config('test.uid','${user}',false);`);
 const document={run_date:'2026-07-01',source_digest:'a'.repeat(64),filename:'Run.docx',snapshot:{paragraphs:[]},rows:[{source_index:0,raw_text:'Demo planned',section:'Work',struck:false,job_id:job},{source_index:1,raw_text:'Waiting',section:'TBS',struck:true,job_id:null}]};
 const history=async(d=document,office='IE')=>(await db.query('select import_run_history($1,$2::jsonb) as id',[office,JSON.stringify(d)])).rows[0].id;
 const docId=await history();assert.equal(await history(),docId);
 assert.equal((await db.query('select * from run_history_rows')).rows.length,2);
 const row=(await db.query('select * from run_history_rows where source_index=1')).rows[0];
 const relink=async(j,rev)=>(await db.query('select link_run_history($1,$2,$3) as rev',[row.id,j,rev])).rows[0].rev;
 assert.equal(await relink(job,1),2);assert.equal(await relink(job,1),2);
 await assert.rejects(relink(null,1),/changed elsewhere/);
 await assert.rejects(relink('20000000-0000-4000-8000-000000000002',2),/unavailable/);
 assert.equal(await relink(null,2),3);
 await assert.rejects(db.query("update run_history_rows set raw_text='changed'"),/permission denied/);
 await assert.rejects(history(document,'OTHER'),/Office access/);
 await assert.rejects(history({...document,source_digest:'b'.repeat(64),rows:[{...document.rows[0],job_id:'20000000-0000-4000-8000-000000000002'}]}),/unavailable/);
 assert.equal((await db.query('select * from run_history_documents')).rows.length,1);
 await db.exec("select set_config('test.uid','10000000-0000-4000-8000-000000000099',false)");
 assert.equal((await db.query('select * from run_history_documents')).rows.length,0);
 assert.equal((await db.query('select * from run_history_rows')).rows.length,0);
 assert.equal((await db.query('select * from run_history_link_changes')).rows.length,0);
 await assert.rejects(relink(job,3),/Office access/);
 await db.close(); console.log('Schedule SQL and immutable Run history: retries, link revisions, rollback and RLS passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
