"""The config baked into the .exe must be complete AND carry no personal
credentials.

`_packaging/config.json` seeds %APPDATA%\\Linguar Hub\\config.json on a new
machine's first run. It was hand-maintained and had drifted: no Supabase
credentials, no department profiles, no franchise identity — a fresh
install could not reach the shared job database or match a Trello card.
It is generated by `_packaging/make_shipped_config.py` now; this is the
guard on what that produces.

Both directions matter. Missing a shared key means a coworker's install
is broken on arrival. Including a personal one means shipping somebody's
Trello identity to everyone who installs it.
"""
import json
import os

import pytest

_SCRIPTS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SHIPPED = os.path.join(_SCRIPTS, "_packaging", "config.json")


@pytest.fixture(scope="module")
def cfg():
    with open(_SHIPPED, encoding="utf-8") as f:
        return json.load(f)


# ── must be present, or a new install is dead on arrival ───────────────
@pytest.mark.parametrize("key", [
    "supabase_url",            # shared job DB — the whole point of the trial
    "supabase_anon_key",
    "trello_api_key",          # identifies the APP; without it Connect fails
    "trello_workspace_id",
    "audit_base",
    "active_department",
    "multi_department_enabled",
    "franchise_name",
    "office_phone",
])
def test_shared_key_ships(cfg, key):
    assert cfg.get(key) not in (None, ""), f"{key} missing from shipped config"


def test_department_profiles_ship(cfg):
    """Each department must at least carry its own Trello workspace — that
    is what keeps IE from searching OC's boards.

    A blank `trello_api_key` on a profile is legitimate: it inherits the
    base key, which is the same Trello APP for both franchises. What must
    never be blank is the workspace id (see the department-separation
    guard — IE inheriting base's workspace broke all card matching)."""
    depts = cfg.get("departments") or {}
    assert set(depts) >= {"IE", "OC"}
    for name, prof in depts.items():
        assert prof.get("trello_workspace_id"), f"{name} has no workspace id"
    assert cfg.get("trello_api_key"), "no base Trello key for profiles to inherit"


def test_ie_identity_is_not_a_placeholder(cfg):
    """IE's profile said franchise_name="OC Office" with a blank phone, and
    the department overlay beats the base — so IE paperwork carried the
    wrong franchise and no phone number."""
    ie = cfg["departments"]["IE"]
    assert "SERVPRO" in ie["franchise_name"].upper()
    assert ie["franchise_name"] != "OC Office"
    assert ie.get("office_phone")


# ── must NOT be present, or we ship someone's identity ─────────────────
def test_personal_tokens_are_blank(cfg):
    assert cfg.get("trello_token") == ""
    assert cfg.get("companycam_api_token") == ""
    for name, prof in (cfg.get("departments") or {}).items():
        assert prof.get("trello_token", "") == "", \
            f"departments.{name}.trello_token would ship"


def test_no_service_role_key_anywhere(cfg):
    """The anon key is safe to ship — no RLS policy grants `anon` anything.
    A service_role key bypasses RLS entirely and must never be in here."""
    blob = json.dumps(cfg).lower()
    for bad in ("service_role", "sbp_", "secret"):
        assert bad not in blob, f"shipped config contains {bad!r}"
    key = cfg["supabase_anon_key"]
    assert key.startswith("sb_publishable_") or key.startswith("ey")


def test_no_user_profile_paths(cfg):
    """Shipping this machine's OneDrive path would point every install at a
    folder that doesn't exist. paths.auto_detect() recovers these per PC."""
    def walk(o, trail="root"):
        if isinstance(o, str):
            low = o.replace("/", "\\").lower()
            assert ":\\users\\" not in low, f"{trail} hard-codes {o}"
        elif isinstance(o, dict):
            for k, v in o.items():
                walk(v, f"{trail}.{k}")
        elif isinstance(o, list):
            for i, v in enumerate(o):
                walk(v, f"{trail}[{i}]")
    walk(cfg)


def test_machine_local_keys_are_absent(cfg):
    for key in ("runs_dir", "photos_root", "snapshot_output",
                "pythonw", "scripts_dir", "dept_browsers"):
        assert not cfg.get(key), f"{key} is machine-local and must not ship"


# ── the generator itself ───────────────────────────────────────────────
def test_generator_classifies_every_live_key():
    """Any key added to config.json later must be explicitly classified as
    SHARE / PER_USER / MACHINE_LOCAL — otherwise a future shared setting
    silently stops shipping, or a future secret silently starts."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "_mkcfg", os.path.join(_SCRIPTS, "_packaging",
                               "make_shipped_config.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    with open(_SHIPPED, encoding="utf-8") as f:
        shipped = json.load(f)
    out, unclassified = mod.build(shipped)
    assert not unclassified, f"unclassified keys: {unclassified}"
    assert not mod.audit(out), mod.audit(out)
