const state={data:null,view:"home",board:"wip",jobFilter:"all",query:"",selectedClient:"",clientAccount:null,selectedJob:null,jobContext:null,connections:[],fieldNoteTemplates:{},toolRoutes:{},accessKey:"",dispatchEditStarted:0};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const attr=esc;
let transportMode="",transportProbe=null;

document.addEventListener("DOMContentLoaded",()=>{bind();tick();setInterval(tick,30000);boot();});

function bind(){
  $$("[data-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
  $("[data-refresh]").addEventListener("click",()=>boot(true));
  $("[data-go-jobs]").addEventListener("click",()=>showView("jobs"));
  $("[data-go-dispatch]").addEventListener("click",()=>showView("dispatch"));
  $("[data-edit-dispatch]")?.addEventListener("click",event=>{state.dispatchEditStarted=Date.now();launchTool("run_doc_editor_web",event.currentTarget);});
  $("[data-job-filter]").addEventListener("change",e=>{state.jobFilter=e.target.value;renderJobs();});
  $(".global-search input").addEventListener("input",e=>{state.query=e.target.value.trim().toLowerCase();if(state.view==="clients")renderClientList();else{showView("jobs");renderJobs();}});
  $("[data-client-search]").addEventListener("input",e=>{state.query=e.target.value.trim().toLowerCase();renderClientList();});
  $$("[data-filter-job]").forEach(b=>b.addEventListener("click",()=>{state.jobFilter=b.dataset.filterJob;showView("jobs");renderJobs();}));
  $("[data-job-drawer]").addEventListener("click",e=>{if(e.target.closest("[data-drawer-close]"))closeDrawer();});
  $("[data-job-backdrop]").addEventListener("click",closeDrawer);
  $("[data-client-record]").addEventListener("click",event=>{const button=event.target.closest(".record-actions .primary-action");if(button)launchTool("new_job",button);});
  $("[data-tools-toggle]").addEventListener("click",e=>{e.stopPropagation();toggleTools();});
  $$('[data-tool]').forEach(button=>button.addEventListener("click",()=>launchTool(button.dataset.tool,button)));
  $$('[data-open-settings]').forEach(button=>button.addEventListener("click",openSettings));
  $('[data-settings-refresh]')?.addEventListener("click",loadConnections);
  $('[data-advanced-settings]')?.addEventListener("click",event=>launchTool("settings_web",event.currentTarget));
  $$('[data-account-close]').forEach(button=>button.addEventListener("click",closeAccountModal));
  $('[data-account-modal]')?.addEventListener("click",event=>{if(event.target===event.currentTarget)closeAccountModal();});
  $('[data-account-form]')?.addEventListener("submit",submitAccountSignIn);
  document.addEventListener("click",e=>{if(!e.target.closest(".tools-anchor"))closeTools();});
  window.addEventListener("focus",()=>{if(state.dispatchEditStarted&&Date.now()-state.dispatchEditStarted>1000){state.dispatchEditStarted=0;boot(true);}});
  document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$(".global-search input").focus();}if(e.key==="Escape"){closeTools();if(!$('[data-account-modal]')?.hidden)closeAccountModal();else{const editor=$("[data-requirement-editor]");if(editor)editor.remove();else closeDrawer();}}});
  $(".new-loss").addEventListener("click",e=>launchTool("new_job",e.currentTarget));
  const queryKey=new URLSearchParams(location.search).get("key")||sessionStorage.getItem("operations-key")||"";
  if(queryKey){state.accessKey=queryKey;sessionStorage.setItem("operations-key",queryKey);}
}

async function parseJsonResponse(response,url){
  const contentType=String(response.headers.get("content-type")||"").toLowerCase();
  const text=await response.text();
  if(!contentType.includes("application/json")){
    const returnedApp=/<!doctype|<html/i.test(text);
    throw new Error(returnedApp?`The desktop bridge is still starting (${url}). Try Refresh.`:`${url} returned ${contentType||"an unknown format"}, not JSON.`);
  }
  try{return text?JSON.parse(text):{};}catch(_){throw new Error(`${url} returned invalid JSON.`);}
}

async function resolveTransport(){
  if(window.pywebview?.api)return "desktop";
  if(transportMode)return transportMode;
  if(!transportProbe)transportProbe=(async()=>{
    let readyResolve;
    const nativeReady=new Promise(resolve=>{readyResolve=resolve;setTimeout(()=>resolve(""),5000);});
    window.addEventListener("pywebviewready",()=>readyResolve("desktop"),{once:true});
    try{
      const response=await fetch("/api/health",{cache:"no-store"});
      const payload=await parseJsonResponse(response,"/api/health");
      if(payload?.ok)return "browser";
    }catch(_){
      // A pywebview static server returns index.html for unknown routes.
      // Wait for the native bridge instead of parsing that page as JSON.
    }
    if(window.pywebview?.api)return "desktop";
    const ready=await nativeReady;
    if(ready&&window.pywebview?.api)return "desktop";
    throw new Error("The Operations Hub connection did not finish starting.");
  })();
  transportMode=await transportProbe;
  return transportMode;
}

async function transport(method,...args){
  const mode=await resolveTransport();
  if(mode==="desktop"&&window.pywebview?.api?.[method])return window.pywebview.api[method](...args);
  const reads=["bootstrap","client_account","job_context","connections","field_note_templates","tool_routes"],writes=["set_job_requirement","save_job_update","save_field_note","import_job_log","job_action","account_sign_in","account_sign_out","begin_connection"];
  if(!reads.includes(method)&&!writes.includes(method))return {ok:false,error:"This action is available in the desktop app."};
  const headers={...(state.accessKey?{"X-Operations-Key":state.accessKey}:{}),...(writes.includes(method)?{"Content-Type":"application/json"}:{})};
  let url=method==="bootstrap"?`/api/bootstrap?force=${args[0]?1:0}`:method==="job_context"?`/api/job?client=${encodeURIComponent(args[0]||"")}&card_id=${encodeURIComponent(args[1]||"")}&division=${encodeURIComponent(args[2]||"EMS")}`:method==="client_account"?`/api/client?name=${encodeURIComponent(args[0]||"")}`:method==="connections"?"/api/connections":method==="field_note_templates"?`/api/field-note-templates?division=${encodeURIComponent(args[0]||"EMS")}`:method==="tool_routes"?"/api/operations-tools":method==="set_job_requirement"?"/api/requirement":method==="save_field_note"?"/api/field-note":method==="import_job_log"?"/api/job-log-import":method==="job_action"?"/api/job-action":method==="account_sign_in"?"/api/account-sign-in":method==="account_sign_out"?"/api/account-sign-out":method==="begin_connection"?"/api/connection-action":"/api/job-update";
  const body=method==="set_job_requirement"?JSON.stringify({client:args[0]||"",requirement_key:args[1]||"",state:args[2]||"",note:args[3]||"",details:args[4]||{},card_id:args[5]||"",division:args[6]||"EMS"}):method==="save_job_update"?JSON.stringify({client:args[0]||"",entry:args[1]||{}}):method==="save_field_note"?JSON.stringify({client:args[0]||"",note_type:args[1]||"",values:args[2]||{},division:args[3]||"EMS",source_id:args[4]||""}):method==="import_job_log"?JSON.stringify({client:args[0]||"",card_id:args[1]||""}):method==="job_action"?JSON.stringify({action:args[0]||"",job:args[1]||{}}):method==="account_sign_in"?JSON.stringify({email:args[0]||"",password:args[1]||""}):method==="account_sign_out"?"{}":method==="begin_connection"?JSON.stringify({provider:args[0]||""}):undefined;
  const response=await fetch(url,{headers,method:writes.includes(method)?"POST":"GET",body});
  if(response.status===401&&!state.accessKey){const key=prompt("Enter the Operations Hub access key");if(key){state.accessKey=key;sessionStorage.setItem("operations-key",key);return transport(method,...args);}}
  return parseJsonResponse(response,url);
}

async function boot(force=false){
  const button=$("[data-refresh]");button.disabled=true;button.textContent="↻";setStatus(force?"Refreshing live operations…":"Loading the operating picture…");
  try{
    const data=await transport("bootstrap",force);
    if(!data?.ok)throw new Error(data?.error||data?.warnings?.join(" · ")||"Operations data unavailable");
    state.data=data;state.toolRoutes=data.tool_routes||state.toolRoutes;renderAll();
    const shared=data.data_state||{},sharedReady=shared.mode==="shared";
    $(".connection-dot").classList.toggle("ok",sharedReady);
    $("[data-connection]").textContent=sharedReady?"Supabase connected":shared.fallback==="folders"?"Folders · sign-in needed":data.pipeline_source==="trello"?"Trello reference":"Needs attention";
    setStatus((data.warnings||[]).join(" · ")||`${data.overview.active_jobs} live jobs loaded`);
    $("[data-load-time]").textContent=`${data.load_ms||0} ms${data.cached?" · cached":""}`;
  }catch(error){setStatus(String(error),true);$("[data-connection]").textContent="Needs attention";toast(`Operations data could not load: ${error}`);}
  finally{button.disabled=false;}
}

function renderAll(){renderSignals();renderHome();renderBoardTabs();renderJobs();renderDispatch();renderClientList();renderReports();}
function renderSignals(){
  const d=state.data, o=d.overview;
  ["EMS","CONTENTS","RECON"].forEach(x=>$( `[data-signal="${x}"]`).textContent=o.divisions[x]||0);
  $$('[data-metric]').forEach(el=>el.textContent=o[el.dataset.metric]??0);
  $("[data-job-count]").textContent=o.active_jobs;$("[data-updated]").textContent=`Updated ${fmtTime(d.generated_at)} · ${d.source}`;$("[data-source]").textContent=`${o.active_jobs} active · ${o.clients} clients`;
}

function renderHome(){
  const d=state.data,o=d.overview;
  const priority=d.jobs.filter(j=>j.overdue||j.stall==="bad"||j.stall==="warn").sort((a,b)=>Number(b.overdue)-Number(a.overdue)||b.days_in_lane-a.days_in_lane).slice(0,7);
  $("[data-priority-feed]").innerHTML=priority.length?priority.map(j=>`<button type="button" class="priority-row" data-open-job="${attr(j.card_id)}"><i aria-hidden="true"></i><span><strong>${esc(j.client)}</strong><small>${esc(j.board)} · ${esc(j.lane)}</small></span><b>${j.overdue?"OVERDUE":j.days_in_lane+"D"}</b></button>`).join(""):`<div class="dispatch-empty">No jobs currently need escalation.</div>`;
  wireJobs($("[data-priority-feed]"));
  const today=d.dispatch.days[0]?.jobs||[];$("[data-today-scheduled]").textContent=today.length;$("[data-unscheduled]").textContent=d.dispatch.unscheduled_count;$("[data-today]").textContent=new Date().toLocaleDateString([], {month:"short",day:"numeric"});
  $("[data-day-meter]").style.width=`${Math.min(100,Math.round(today.length/Math.max(1,today.length+d.dispatch.unscheduled_count)*100))}%`;
  const top=d.reports.lane_counts.slice(0,8), max=Math.max(1,...top.map(x=>x.value));
  $("[data-lane-summary]").innerHTML=top.map(x=>`<div class="lane-summary-card"><strong>${x.value}</strong><span>${esc(x.label)}</span><small>${Math.round(x.value/max*100)}% of busiest lane</small></div>`).join("");
}

function renderBoardTabs(){
  const boards=state.data.boards.filter(b=>b.key!=="logs");if(!boards.some(b=>b.key===state.board))state.board=boards[0]?.key||"";
  $("[data-board-tabs]").innerHTML=boards.map(b=>`<button class="${b.key===state.board?"active":""}" data-board-tab="${attr(b.key)}">${esc(shortBoard(b.name))}</button>`).join("");
  $$('[data-board-tab]').forEach(b=>b.addEventListener("click",()=>{state.board=b.dataset.boardTab;renderBoardTabs();renderJobs();}));
}

function renderJobs(){
  if(!state.data)return;const board=state.data.boards.find(b=>b.key===state.board);const host=$("[data-jobs-board]");if(!board){host.innerHTML="<div class='dispatch-empty'>No board available.</div>";return;}
  host.innerHTML=(board.lanes||[]).map(l=>{let cards=(l.cards||[]).filter(jobMatches);return `<section class="job-lane"><header><strong>${esc(l.name)}</strong><b>${cards.length}</b></header><div class="job-cards">${cards.map(c=>jobCard(c,board.key)).join("")||"<div class='dispatch-empty'>No matching jobs</div>"}</div></section>`}).join("");wireJobs(host);enableHorizontalGrab(host);
}
function jobMatches(j){const q=state.query,haystack=`${j.client} ${j.job_name||""} ${j.account_client||""} ${j.claim_number||""} ${j.carrier||""} ${(j.loss_types||[]).join(" ")}`.toLowerCase(),matchQ=!q||haystack.includes(q);const f=state.jobFilter;return matchQ&&(f==="all"||f==="attention"&&(j.overdue||j.stall==="warn"||j.stall==="bad")||f==="overdue"&&j.overdue||f==="stalled"&&(j.stall==="warn"||j.stall==="bad")||f==="today"&&j.due===todayIso());}
function jobCard(j,boardKey=j.board_key){const division=boardKey==="contents"?"CONTENTS":"EMS",title=j.job_name||j.client,account=j.account_client&&j.account_client!==title?`<small>${esc(j.account_client)}</small>`:"";return `<button type="button" class="job-card ${j.overdue||j.stall==="bad"?"attention":""}" data-open-job="${attr(j.card_id)}"><strong>${esc(title)}</strong>${account}<span class="job-card-meta"><span class="pill ${division.toLowerCase()}">${division}</span>${j.overdue?"<span class='pill overdue'>Overdue</span>":""}${j.days_in_lane?`<span class="pill stall">${j.days_in_lane}d in lane</span>`:""}${j.carrier?`<span class="pill">${esc(j.carrier)}</span>`:(j.loss_types||[]).slice(0,1).map(x=>`<span class="pill">${esc(x)}</span>`).join("")}${j.identity_state==="unlinked"?"<span class='pill overdue'>Needs link</span>":""}</span></button>`;}

function renderDispatch(){
  const d=state.data.dispatch,grid=$("[data-dispatch-grid]");
  grid.innerHTML=d.days.map((day,i)=>`<section class="dispatch-day ${i===0?"today":""}"><header><div><strong>${esc(day.label)}</strong><small>${fmtDate(day.date)}</small></div><b>${day.jobs.length}</b></header><div class="dispatch-day-list">${day.jobs.map(j=>dispatchCard(j)).join("")||(day.exists?"<div class='dispatch-empty'>No assignments</div>":"<div class='dispatch-empty'>No Run Doc found</div>")}</div></section>`).join("");
  $("[data-unscheduled-count]").textContent=d.unscheduled_count;
  $("[data-unscheduled-list]").innerHTML=d.unscheduled.slice(0,20).map(j=>jobCard(j,j.board_key)).join("")||"<div class='dispatch-empty'>Every active job is scheduled.</div>";
  wireJobs($("[data-panel='dispatch']"));enableHorizontalGrab(grid);
}
function dispatchCard(j){
  const meta=[j.time_slot,j.section==="monitor"?"Monitor":"Work"].filter(Boolean).join(" · "),techs=(j.technicians||[]).join(", ")||"Technician not assigned",warning=!j.matched?"Not linked to a job":j.match_conflict?"Multiple job matches — review link":"";
  const open=j.card_id?` data-open-job="${attr(j.card_id)}"`:"";
  return `<button type="button" class="dispatch-job ${j.division==="CONTENTS"?"contents":""} ${!j.matched||j.match_conflict?"unlinked":""}"${open}><strong>${esc(j.client)}</strong><small>${esc(meta)}</small><small class="dispatch-techs">${esc(techs)}</small>${warning?`<small class="dispatch-warning">${esc(warning)}</small>`:""}</button>`;
}

function renderClientList(){if(!state.data)return;const q=state.query;const rows=state.data.clients.filter(c=>!q||c.name.toLowerCase().includes(q)).slice(0,300);$("[data-client-list]").innerHTML=rows.map(c=>`<button class="client-row ${state.selectedClient===c.name?"active":""}" data-client="${attr(c.name)}"><span class="client-initial">${esc(initials(c.name))}</span><div><strong>${esc(c.name)}</strong><small>${c.job_count||0} job${c.job_count===1?"":"s"} · ${(c.divisions||[]).map(shortDivision).join(" · ")||"Unclassified"}</small></div></button>`).join("")||"<div class='dispatch-empty'>No clients found.</div>";$$('[data-client]').forEach(b=>b.addEventListener("click",()=>openClient(b.dataset.client)));}
async function openClient(name){state.selectedClient=name;state.clientAccount=null;renderClientList();const host=$("[data-client-record]");host.innerHTML="<div class='empty-record'><span>◌</span><h2>Opening client…</h2><p>Resolving the referenced job to its client account.</p></div>";try{const r=await transport("client_account",name);if(!r?.ok)throw new Error(r?.error||"Client unavailable");state.clientAccount=r;const account=clientIdentity(r);state.selectedClient=account.name||name;renderClientList();host.innerHTML=clientRecord(r);$$('[data-open-folder]',host).forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();desktopAction("open_folder",b.dataset.openFolder);}));$$('[data-client-job]',host).forEach(b=>{b.addEventListener("click",()=>openClientJob(b.dataset.clientJob));b.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openClientJob(b.dataset.clientJob);}});});}catch(e){host.innerHTML=`<div class="empty-record"><span>!</span><h2>Client could not open</h2><p>${esc(e instanceof Error?e.message:e)}</p></div>`;}}
function clientIdentity(r){if(r?.client&&typeof r.client==="object")return r.client;return {name:r?.display_name||r?.client||r?.resolved_client_name||"Client",folder:r?.folder||"",phone:r?.phone||"",email:r?.email||"",address:r?.address||"",franchise:r?.franchise||""};}
function clientRecord(r){const account=clientIdentity(r),jobs=r.jobs||[],divisions=[...new Set(jobs.flatMap(j=>j.divisions||[]))],reference=r.requested_reference?`<div class="reference-resolution"><strong>Referenced job matched to this client</strong><span>${esc(r.requested_reference)}</span></div>`:"";return `${reference}<header class="record-head"><span class="record-monogram">${esc(initials(account.name))}</span><div class="record-head-copy"><h2>${esc(account.name)}</h2><p>${jobs.length} claims/jobs · ${divisions.map(shortDivision).join(" · ")||"Division details below"}</p></div><div class="record-actions">${account.folder?`<button class="quiet-button" data-open-folder="${attr(account.folder)}">Open client folder</button>`:""}<button class="primary-action">Add job</button></div></header>${account.phone||account.email||account.address?`<div class="client-facts">${fact("Phone",account.phone)}${fact("Email",account.email)}${fact("Address",account.address)}${fact("Franchise",account.franchise)}</div>`:""}<div class="record-jobs">${jobs.map((j,index)=>`<article class="claim-card" tabindex="0" role="button" data-client-job="${attr(j.key||String(index))}"><header><div><h3>${esc(j.name)}</h3><small>${esc(j.kind||"Job")}${j.date_received?` · Received ${esc(j.date_received)}`:""}</small></div><span class="division-badges">${(j.divisions||[]).map(d=>`<b class="${String(d).toUpperCase()==="CONTENTS"?"contents":String(d).toUpperCase()==="RECON"?"recon":""}">${esc(shortDivision(String(d).toUpperCase()))}</b>`).join("")}</span></header><div class="claim-facts">${fact("Claim",j.claim_number)}${fact("Carrier",j.carrier)}${fact("Loss date",j.date_of_loss)}${fact("Status",j.status||"Recorded")}</div><footer><span>Open job details</span>${j.folder_exists?`<button class="text-button" data-open-folder="${attr(j.path)}">Open folder</button>`:""}</footer></article>`).join("")||"<div class='dispatch-empty'>No claim records found for this client.</div>"}</div>${renderClientLog(r.job_log||[])}`;}
function renderClientLog(entries){return `<section class="client-history"><div class="section-heading"><div><small>Account history</small><h2>Job Log</h2></div><strong>${entries.length}</strong></div><div class="job-log-preview">${entries.slice(0,20).map(entry=>`<article><header><strong>${esc(entry.work_type||"Job update")}</strong><time>${fmtDate(entry.work_date||entry.created_at)}</time></header><p>${esc(entry.note||entry.status||"Saved update")}</p></article>`).join("")||`<p class="muted">No saved job-log entries for this client yet.</p>`}</div></section>`;}
function openClientJob(key){const r=state.clientAccount;if(!r)return;const account=clientIdentity(r),jobs=r.jobs||[],jobRecord=jobs.find((job,index)=>String(job.key||index)===String(key));if(!jobRecord)return;const live=(state.data?.jobs||[]).find(job=>job.client===jobRecord.name||job.client===account.name||job.client.includes(jobRecord.name));if(live){openJob(live.card_id);return;}const division=String(jobRecord.divisions?.[0]||"EMS").toUpperCase();const fields=[["Claim",jobRecord.claim_number],["Carrier",jobRecord.carrier],["Date of loss",jobRecord.date_of_loss],["Date received",jobRecord.date_received],["Cause of loss",jobRecord.cause_of_loss],["Property",jobRecord.property],["Status",jobRecord.status]].filter(([,value])=>value).map(([label,value],index)=>({id:`history_${index}`,label,value}));const historical={card_id:`history:${jobRecord.key||key}`,client:jobRecord.name||account.name,account_client:account.name,division,board:"Client history",lane:jobRecord.status||"Recorded",days_in_lane:0,due:"",last_activity_at:"",path:jobRecord.path||""};state.selectedJob=historical;state.jobContext={ok:true,client:historical.client,division,path:historical.path,fields,job_log:r.job_log||[],progress:{items:[],counts:{},percent_complete:0},historical:true,load_ms:0};renderJobDrawer(historical,state.jobContext);}
function fact(label,value){return `<div><small>${esc(label)}</small><strong>${esc(value||"—")}</strong></div>`;}

function renderReports(){const r=state.data.reports;renderBars($("[data-division-chart]"),Object.entries(r.division_counts).map(([label,value])=>({label,value})),true);renderBars($("[data-age-chart]"),r.age_bands);$("[data-lane-report]").innerHTML=r.lane_counts.slice(0,12).map((x,i)=>`<div class="rank-row"><span>${String(i+1).padStart(2,"0")}</span><strong>${esc(x.label)}</strong><b>${x.value}</b></div>`).join("");}
function renderBars(host,rows,division=false){const max=Math.max(1,...rows.map(x=>x.value));host.innerHTML=rows.map(x=>`<div class="bar-row ${division?x.label.toLowerCase():""}"><span>${esc(shortDivision(x.label))}</span><i><b style="width:${Math.round(x.value/max*100)}%"></b></i><strong>${x.value}</strong></div>`).join("");}

function showView(view){state.view=view;$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===view));$$('[data-open-settings]').forEach(b=>b.classList.toggle("active",view==="settings"));$$('[data-panel]').forEach(p=>p.classList.toggle("active",p.dataset.panel===view));const titles={home:["Office workflow","Operations"],jobs:["Active claims","Jobs"],dispatch:["Next 7 days","Dispatch"],clients:["Accounts & claim history","Clients"],reports:["Current workload","Reports"],settings:["Account & local setup","Settings"]};const title=titles[view]||titles.home;$("[data-eyebrow]").textContent=title[0];$("[data-title]").textContent=title[1];if(view==="settings")loadConnections();}
function wireJobs(root){$$('[data-open-job]',root).forEach(el=>el.addEventListener("click",event=>{const board=el.closest(".jobs-board");if(board&&performance.now()<(board._suppressClickUntil||0)){event.preventDefault();return;}openJob(el.dataset.openJob);}));}

function enableHorizontalGrab(host){
  if(!host||host._grabBound)return;host._grabBound=true;let gesture=null;
  host.addEventListener("pointerdown",event=>{const control=event.target.closest("button,input,select,textarea,a,summary");if(event.button!==0||(control&&!control.matches(".job-card,.dispatch-job"))||event.clientY>=host.getBoundingClientRect().bottom-14)return;gesture={id:event.pointerId,x:event.clientX,y:event.clientY,left:host.scrollLeft,axis:"",moved:false};if(event.pointerType==="mouse"){try{host.setPointerCapture(event.pointerId);}catch(_){}}});
  host.addEventListener("pointermove",event=>{if(!gesture||gesture.id!==event.pointerId)return;const dx=event.clientX-gesture.x,dy=event.clientY-gesture.y;if(!gesture.axis&&Math.hypot(dx,dy)>3)gesture.axis=Math.abs(dx)>=Math.abs(dy)?"x":"y";if(gesture.axis!=="x")return;event.preventDefault();gesture.moved=true;host.classList.add("is-grabbing");try{host.setPointerCapture(event.pointerId);}catch(_){}host.scrollLeft=gesture.left-dx;});
  const finish=event=>{if(!gesture||gesture.id!==event.pointerId)return;if(gesture.moved)host._suppressClickUntil=performance.now()+180;gesture=null;host.classList.remove("is-grabbing");};
  host.addEventListener("pointerup",finish);host.addEventListener("pointercancel",finish);host.addEventListener("lostpointercapture",event=>{if(gesture&&gesture.id===event.pointerId){gesture=null;host.classList.remove("is-grabbing");}});
  host.addEventListener("wheel",event=>{const horizontal=Math.abs(event.deltaX)>Math.abs(event.deltaY);if(horizontal){event.preventDefault();host.scrollLeft+=event.deltaX;}else if(event.shiftKey){event.preventDefault();host.scrollLeft+=event.deltaY;}},{passive:false});
}

function openSettings(){closeTools();showView("settings");}
async function loadConnections(){const host=$("[data-operations-connections]"),message=$("[data-settings-message]");if(!host)return;host.innerHTML='<div class="settings-loading"><i></i><span>Checking your connections…</span></div>';if(message)message.textContent="";let result;try{result=await transport("connections");}catch(error){result={ok:false,error:String(error)};}if(!result?.ok){host.innerHTML='<div class="settings-empty">Connections could not be checked.</div>';if(message)message.textContent=result?.error||"";return;}state.connections=result.connections||[];host.innerHTML=state.connections.map(connectionCard).join("");$$('[data-connection-action]',host).forEach(button=>button.addEventListener("click",()=>runConnectionAction(button)));}
function serviceIcon(provider,fallback=""){const src={trello:"../web_shared/trello.png",companycam:"../web_shared/companycam.png",xa:"../web_shared/xactanalysis.png"}[provider];return src?`<img class="service-icon" src="${src}" width="18" height="18" alt="">`:esc(fallback);}
function connectionCard(card){const button=card.action?`<button class="quiet-button ${card.state==="connected"?"":"connection-primary"}" data-provider="${attr(card.provider)}" data-connection-action="${attr(card.action)}">${esc(card.action_label)}</button>`:"";return `<article class="operations-connection" data-state="${attr(card.state)}"><span class="operations-connection-mark">${serviceIcon(card.provider,card.icon)}</span><div><header><strong>${esc(card.name)}</strong><b>${esc(card.status)}</b></header><p>${esc(card.detail)}</p>${card.identity?`<small>${esc(card.identity)}</small>`:""}${button}</div></article>`;}
async function runConnectionAction(button){const action=button.dataset.connectionAction,provider=button.dataset.provider;if(action==="sign_in"){openAccountModal();return;}if(action==="sign_out"){button.disabled=true;const result=await transport("account_sign_out");toast(result?.ok?result.message:(result?.error||"Could not sign out"));await loadConnections();return;}if(action==="admin_setup"){launchTool("settings_web",button);return;}const label=button.textContent;button.disabled=true;button.textContent=action==="connect_trello"?"Waiting for sign in…":"Opening…";const result=await transport("begin_connection",provider);button.disabled=false;button.textContent=label;if(result?.url)desktopAction("open_url",result.url);toast(result?.ok?(result.message||"Opened"):(result?.error||"Could not connect"));if(result?.ok)await loadConnections();}
function openAccountModal(){$("[data-account-modal]").hidden=false;setTimeout(()=>$("[data-account-form] input[name='email']")?.focus(),0);}
function closeAccountModal(){$("[data-account-modal]").hidden=true;$("[data-account-error]").textContent="";}
async function submitAccountSignIn(event){event.preventDefault();const form=event.currentTarget,submit=$("button[type='submit']",form),error=$("[data-account-error]",form),values=new FormData(form);submit.disabled=true;submit.textContent="Signing in…";error.textContent="";const result=await transport("account_sign_in",String(values.get("email")||""),String(values.get("password")||""));submit.disabled=false;submit.textContent="Sign in";if(!result?.ok){error.textContent=result?.error||"Sign in failed";form.elements.password.select();return;}form.reset();closeAccountModal();toast(result.message||"Signed in");await loadConnections();boot(true);}
function openJob(id){const job=state.data.jobs.find(j=>j.card_id===id);if(!job)return;state.selectedJob=job;state.jobContext=null;renderJobDrawer(job);loadJobContext(job);}
function renderJobDrawer(job,context=state.jobContext){
  const drawer=$("[data-job-drawer]"),progress=context?.progress||{},counts=progress.counts||{},fields=context?.fields||[];
  const copyFields=fields.length?fields:[{id:"job_name",label:"Job name",value:job.client}];
  const copyRows=copyFields.map(field=>`<button data-copy-value="${attr(field.value)}"><span>${esc(field.label)}</span><small>${esc(field.value)}</small></button>`).join("");
  const loadState=context?`${context.load_ms||0} ms`:`Loading saved Job Info…`;
  drawer.innerHTML=`
    <header class="drawer-head">
      <div><small class="drawer-kicker">${esc(job.division)} · ${esc(job.board)}</small><h2>${esc(job.client)}</h2><div class="drawer-meta">${esc(job.lane)} · ${job.days_in_lane} day(s) in lane</div></div>
      <div class="drawer-head-actions"><button class="client-link" data-client-page>Client page</button><button class="drawer-close job-drawer-close" data-drawer-close aria-label="Close job"><span aria-hidden="true">×</span><em>Close</em></button></div>
    </header>
    <div class="job-action-bar" aria-label="Job actions">
      <div class="action-cluster action-primary">
        <button class="job-action primary" data-add-update><i>＋</i>Field note</button>
        <details class="copy-menu"><summary class="job-action"><i>▣</i>Copy <span>⌄</span></summary><div class="copy-panel"><header><strong>Copy job details</strong><small>Uses the saved Job Info record</small></header>${copyRows}<button data-copy-summary><span>Job summary</span><small>All available details</small></button></div></details>
        <button class="job-action" data-job-action="photo_report"><i>▧</i>Photo report</button>
      </div>
      <div class="action-cluster action-destinations" aria-label="Open job in">
        <button class="job-action" data-job-action="folder"><i>▰</i>${context?.path?"Folder":"Find folder"}</button>
        ${job.url?`<button class="job-action destination" data-trello>${serviceIcon("trello")}Trello</button>`:""}
        <button class="job-action destination" data-job-action="xa">${serviceIcon("xa")}XA</button>
        <button class="job-action destination" data-job-action="companycam">${serviceIcon("companycam")}CompanyCam</button>
      </div>
    </div>
    <section class="update-composer" data-update-composer hidden></section>
    <div class="drawer-scroll">
      <section class="drawer-section"><div class="drawer-section-title"><h3>Operating status</h3><small>${esc(loadState)}</small></div><div class="drawer-facts">${fact("Division",job.division)}${fact("Current lane",job.lane)}${fact("Due",job.due?fmtDate(job.due):"Not scheduled")}${fact("Last activity",job.last_activity_at?fmtDate(job.last_activity_at):"—")}</div></section>
      ${context?renderProgress(progress,counts):`<section class="drawer-section context-loading"><i></i><div><strong>Loading job workspace</strong><small>Board details are ready; saved Job Info and requirements are loading.</small></div></section>`}
      ${context?renderJobInfo(fields):""}
      ${context?renderJobLog(context.job_log||[]):""}
    </div>`;
  drawer.hidden=false;
  $("[data-job-backdrop]").hidden=false;
  $("[data-client-page]",drawer).addEventListener("click",()=>{const accountName=job.account_client||job.client;closeDrawer();showView("clients");openClient(accountName);});
  $("[data-trello]",drawer)?.addEventListener("click",()=>desktopAction("open_url",context?.trello_url||job.url));
  $$('[data-job-action]',drawer).forEach(button=>button.addEventListener("click",()=>runJobAction(button.dataset.jobAction,button)));
  $("[data-add-update]",drawer).addEventListener("click",()=>showFieldNoteComposer(job));
  $$('[data-copy-value]',drawer).forEach(button=>button.addEventListener("click",()=>copyValue(button.dataset.copyValue,button)));
  $("[data-copy-summary]",drawer)?.addEventListener("click",()=>copyValue(copyFields.map(field=>`${field.label}: ${field.value}`).join("\n"),$("[data-copy-summary]",drawer)));
  bindRequirementActions(drawer);
  bindJobLogActions(drawer,job);
}
function renderProgress(progress,counts=progress.counts||{}){const items=progress.items||[],total=items.filter(item=>["mandatory","required"].includes(item.importance)).length,open=items.filter(item=>!["completed","not_applicable"].includes(item.status)),done=items.filter(item=>["completed","not_applicable"].includes(item.status));const rows=list=>list.map(requirementRow).join("");return `<section class="drawer-section requirements-section" data-requirements-section><div class="drawer-section-title"><div><h3>Requirements</h3><small>${esc(progress.stage_label||"")} · complete work here</small></div><strong>${progress.percent_complete??0}%</strong></div><div class="progress-track"><i style="width:${Math.max(0,Math.min(100,progress.percent_complete||0))}%"></i></div><div class="progress-meta"><span>${counts.todo||0} to do</span><span>${counts.blocked||0} blocked</span><span>${total} required</span></div>${items.length?`<div class="requirement-list">${rows(open)||`<p class="requirement-clear">All active requirements are handled.</p>`}</div>${done.length?`<details class="requirement-done"><summary>Completed or not needed <b>${done.length}</b></summary><div class="requirement-list">${rows(done)}</div></details>`:""}`:`<p class="muted">No requirements are active for this recorded job.</p>`}</section>`;}
function requirementRow(item){const handled=["completed","not_applicable"].includes(item.status),status=item.status==="not_applicable"?"Not needed":item.status==="in_progress"?"In progress":item.status==="blocked"?"Blocked":item.status==="completed"?"Complete":"To do";return `<article class="requirement-item req-${attr(item.status||"todo")}" data-requirement-item="${attr(item.key)}"><span class="requirement-state" aria-hidden="true">${item.status==="completed"?"✓":item.status==="not_applicable"?"—":item.status==="blocked"?"!":item.status==="in_progress"?"◐":"○"}</span><div><strong>${esc(item.label)}</strong><small>${esc(status)} · ${esc(item.owner||"Unassigned")}${item.evidence?` · Evidence: ${esc(item.evidence)}`:""}</small>${item.blocked_reason?`<p>${esc(item.blocked_reason)}</p>`:""}</div><div class="requirement-actions">${handled?"":`<button class="requirement-complete" data-requirement-complete="${attr(item.key)}">Complete</button>`}<button class="requirement-update" data-requirement-update="${attr(item.key)}">${handled?"Update":"More"}</button></div></article>`;}
function bindRequirementActions(root){if(!root)return;$$('[data-requirement-complete]',root).forEach(button=>button.addEventListener("click",()=>saveRequirement(button.dataset.requirementComplete,"completed","",{},button)));$$('[data-requirement-update]',root).forEach(button=>button.addEventListener("click",()=>openRequirementEditor(button.dataset.requirementUpdate)));}
async function saveRequirement(key,nextState,note="",details={},button=null){const job=state.selectedJob;if(!job||!key)return;if(button){button.disabled=true;button.textContent="Saving…";}try{const result=await transport("set_job_requirement",job.client,key,nextState,note,details,job.card_id||"",job.division||"EMS");if(!result?.ok)throw new Error(result?.error||"Requirement could not be updated");if(!state.jobContext)state.jobContext={};state.jobContext.progress=result.progress||state.jobContext.progress||{};const current=$("[data-requirements-section]"),replacement=document.createElement("div");replacement.innerHTML=renderProgress(state.jobContext.progress);current?.replaceWith(replacement.firstElementChild);bindRequirementActions($("[data-requirements-section]"));$("[data-requirement-editor]")?.remove();toast(nextState==="completed"?"Requirement completed":"Requirement updated");}catch(error){toast(String(error instanceof Error?error.message:error));if(button){button.disabled=false;button.textContent=nextState==="completed"?"Complete":"Save changes";}}}
function openRequirementEditor(key){const progress=state.jobContext?.progress||{},item=(progress.items||[]).find(entry=>entry.key===key);if(!item)return;$("[data-requirement-editor]")?.remove();const editor=document.createElement("div");editor.className="requirement-editor-backdrop";editor.dataset.requirementEditor="";editor.innerHTML=`<form class="requirement-editor" role="dialog" aria-modal="true" aria-labelledby="requirement-editor-title"><header><div><small>Requirement</small><h3 id="requirement-editor-title">${esc(item.label)}</h3></div><button type="button" class="drawer-close" data-editor-close aria-label="Close">×</button></header><label>Status<select name="state">${[["todo","To do"],["in_progress","In progress"],["blocked","Blocked"],["completed","Complete"],["not_applicable","Not needed"]].map(([value,label])=>`<option value="${value}" ${item.status===value?"selected":""}>${label}</option>`).join("")}</select></label><div class="requirement-blocked-fields" data-blocked-fields><label>Owner<input name="assignee" value="${attr(item.assignee||"")}" placeholder="Person responsible"></label><label>Follow-up date<input name="follow_up_at" type="date" value="${attr(String(item.follow_up_at||"").slice(0,10))}"></label><label class="wide">What are we waiting for?<input name="blocked_reason" value="${attr(item.blocked_reason||"")}"></label></div><label>Reason or note<textarea name="note" rows="3" placeholder="Required when marking not needed">${esc(item.manual_note||"")}</textarea></label><footer><button type="submit" class="primary-action">Save changes</button><button type="button" class="quiet-button" data-editor-close>Cancel</button></footer><p class="form-error" data-editor-error></p></form>`;$("[data-job-drawer]").append(editor);const form=$("form",editor),select=$("select[name='state']",editor),blocked=$("[data-blocked-fields]",editor);const sync=()=>blocked.hidden=select.value!=="blocked";select.addEventListener("change",sync);sync();$$('[data-editor-close]',editor).forEach(button=>button.addEventListener("click",()=>editor.remove()));editor.addEventListener("click",e=>{if(e.target===editor)editor.remove();});form.addEventListener("submit",async e=>{e.preventDefault();const values=new FormData(form),next=String(values.get("state")||"todo"),note=String(values.get("note")||"").trim(),details={assignee:String(values.get("assignee")||"").trim(),follow_up_at:String(values.get("follow_up_at")||"").trim(),blocked_reason:String(values.get("blocked_reason")||"").trim()};const error=$("[data-editor-error]",editor);if(next==="not_applicable"&&!note){error.textContent="Add a reason before marking this not needed.";return;}if(next==="blocked"&&(!details.assignee||!details.follow_up_at||!details.blocked_reason)){error.textContent="Blocked work needs an owner, reason, and follow-up date.";return;}await saveRequirement(key,next,note,details,$("button[type='submit']",form));});select.focus();}
function renderJobInfo(fields){
  if(!fields.length)return `<section class="drawer-section"><div class="drawer-section-title"><h3>Job Info</h3><small>No saved details yet</small></div><p class="muted">Job Info has not been filled out for this job.</p></section>`;
  const core=fields.filter(field=>field.core!==false),more=fields.filter(field=>field.core===false),rows=list=>`<div class="job-info-grid">${list.map(field=>fact(field.label,field.value)).join("")}</div>`;
  return `<section class="drawer-section"><div class="drawer-section-title"><h3>Job Info</h3><small>${fields.length} saved details</small></div>${rows(core)}${more.length?`<details class="job-info-more"><summary>More job details <b>${more.length}</b></summary>${rows(more)}</details>`:""}</section>`;
}
function renderJobLog(entries){return `<section class="drawer-section" data-job-log-section><div class="drawer-section-title job-log-title"><div><h3>Job log</h3><small>${entries.length} update${entries.length===1?"":"s"} · same history used by Snapshot</small></div><button class="quiet-button" data-import-trello-log>Import Trello</button></div><div class="job-log-preview">${entries.slice(0,8).map(entry=>`<article><header><div><strong>${esc(entry.work_type||"Job update")}</strong><time>${fmtDate(entry.work_date||entry.created_at)}</time></div>${entry.entry_id?`<button class="log-edit" data-edit-log="${attr(entry.entry_id)}">Edit</button>`:""}</header><p>${esc(entry.note||entry.status||"Saved update")}</p>${entry.technicians||entry.updated_by?`<small>${esc([entry.technicians,entry.updated_by].filter(Boolean).join(" · "))}</small>`:""}</article>`).join("")||`<p class="muted">No job-log updates yet. Add one here or import the recognized Trello notes.</p>`}</div></section>`;}
function bindJobLogActions(root,job){$("[data-import-trello-log]",root)?.addEventListener("click",event=>importJobLog(job,event.currentTarget));$$('[data-edit-log]',root).forEach(button=>button.addEventListener("click",()=>{const entry=(state.jobContext?.job_log||[]).find(item=>String(item.entry_id||"")===button.dataset.editLog);if(entry)showUpdateComposer(job,entry);}));}
async function importJobLog(job,button){const label=button.textContent;button.disabled=true;button.textContent="Importing…";try{const result=await transport("import_job_log",job.client,job.card_id||"");if(!result?.ok)throw new Error(result?.error||"Trello notes could not be imported");state.jobContext.job_log=result.job_log||state.jobContext.job_log||[];const current=$("[data-job-log-section]"),replacement=document.createElement("div");replacement.innerHTML=renderJobLog(state.jobContext.job_log);current?.replaceWith(replacement.firstElementChild);bindJobLogActions($("[data-job-log-section]"),job);toast(result.imported?`${result.imported} Trello update(s) imported`:"Job Log is up to date");}catch(error){toast(String(error instanceof Error?error.message:error));button.disabled=false;button.textContent=label;}}
async function loadJobContext(job){try{const result=await transport("job_context",job.client,job.card_id,job.division);if(state.selectedJob?.card_id!==job.card_id)return;if(!result?.ok)throw new Error(result?.error||"Job workspace unavailable");state.jobContext=result;renderJobDrawer(job,result);}catch(error){if(state.selectedJob?.card_id===job.card_id){state.jobContext={fields:[],job_log:[],progress:{},error:String(error)};renderJobDrawer(job,state.jobContext);toast(`Job details: ${error}`);}}}
async function showFieldNoteComposer(job){const host=$("[data-update-composer]");if(!host)return;host.hidden=false;host.classList.add("field-note-host");host.innerHTML=`<div class="field-note-loading"><i></i><span>Preparing field notes…</span></div>`;try{const division=job.division||"EMS",cacheKey=String(division).toUpperCase();let templates=state.fieldNoteTemplates[cacheKey];if(!templates){const result=await transport("field_note_templates",cacheKey);if(!result?.ok)throw new Error(result?.error||"Field notes are unavailable");templates=result.templates||[];state.fieldNoteTemplates[cacheKey]=templates;}if(!templates.length)throw new Error("No field-note templates are configured");renderFieldNoteForm(job,templates,templates[0].key);}catch(error){host.innerHTML=`<div class="composer-heading"><strong>Field notes unavailable</strong><small>${esc(error)}</small></div><button class="quiet-button" data-cancel-update>Close</button>`;$("[data-cancel-update]",host)?.addEventListener("click",()=>{host.hidden=true;host.classList.remove("field-note-host");});}}
function fieldInput(field){const common=`data-field-note-field="${attr(field.name)}" ${field.required?"required":""}`;if(field.type==="textarea")return `<textarea ${common} rows="${Number(field.rows)||2}" placeholder="${attr(field.placeholder||"")}">${esc(field.default||"")}</textarea>`;if(field.type==="select")return `<select ${common}>${(field.options||[]).map(option=>`<option value="${attr(option)}">${esc(String(option||"Choose…").replaceAll("_"," "))}</option>`).join("")}</select>`;return `<input ${common} type="${attr(field.type||"text")}" value="${attr(field.default||"")}" placeholder="${attr(field.placeholder||"")}">`;}
function renderFieldNoteForm(job,templates,activeKey){const host=$("[data-update-composer]"),template=templates.find(item=>item.key===activeKey)||templates[0],primary=(template.fields||[]).filter(field=>field.group!=="details"),details=(template.fields||[]).filter(field=>field.group==="details"),row=field=>`<label class="field-note-field field-${attr(field.type||"text")}"><span>${esc(field.label)}${field.required?" <b>Required</b>":""}</span>${fieldInput(field)}</label>`;host.innerHTML=`<div class="field-note-shell"><header class="field-note-head"><div><small>FIELD NOTE · ${esc(job.division||"EMS")}</small><strong>${esc(job.client)}</strong></div><button class="drawer-close" data-cancel-update aria-label="Close field note">×</button></header><nav class="field-note-types" aria-label="Note type">${templates.map(item=>`<button class="${item.key===template.key?"active":""}" data-field-note-type="${attr(item.key)}"><strong>${esc(item.short_label||item.label)}</strong><small>${esc(item.description)}</small></button>`).join("")}</nav><form data-field-note-form><div class="field-note-intro"><h3>${esc(template.label)}</h3><p>${esc(template.description)}</p></div><div class="field-note-grid">${primary.map(row).join("")}</div>${details.length?`<details class="field-note-details"><summary>Add readings, equipment, or crew details</summary><div class="field-note-grid">${details.map(row).join("")}</div></details>`:""}<footer class="field-note-actions"><button class="primary-action" type="submit">${esc(template.save_label)}</button><button class="quiet-button" type="button" data-cancel-update>Cancel</button><span data-update-status aria-live="polite"></span></footer></form></div>`;$$('[data-field-note-type]',host).forEach(button=>button.addEventListener("click",()=>renderFieldNoteForm(job,templates,button.dataset.fieldNoteType)));$$('[data-cancel-update]',host).forEach(button=>button.addEventListener("click",()=>{host.hidden=true;host.classList.remove("field-note-host");}));$("[data-field-note-form]",host).addEventListener("submit",event=>{event.preventDefault();saveFieldNote(job,template,host);});$("[data-field-note-field]",host)?.focus();}
async function saveFieldNote(job,template,host){const form=$("[data-field-note-form]",host),button=$("button[type='submit']",form),status=$("[data-update-status]",form),values={};$$('[data-field-note-field]',form).forEach(field=>values[field.dataset.fieldNoteField]=field.value);button.disabled=true;const prior=button.textContent;button.textContent="Saving…";status.textContent="";try{const sourceId=globalThis.crypto?.randomUUID?.()||`web-${Date.now()}-${Math.random().toString(16).slice(2)}`,result=await transport("save_field_note",job.client,template.key,values,job.division||"EMS",sourceId);if(!result?.ok)throw new Error(result?.error||"Could not save field note");if(!state.jobContext)state.jobContext={};state.jobContext.job_log=result.entries||[result.entry,...(state.jobContext.job_log||[])];replaceJobLog(job);host.hidden=true;host.classList.remove("field-note-host");toast(`${template.label} saved to Job Log`);}catch(error){button.disabled=false;button.textContent=prior;status.textContent=String(error instanceof Error?error.message:error);}}
function replaceJobLog(job){const current=$("[data-job-log-section]"),replacement=document.createElement("div");replacement.innerHTML=renderJobLog(state.jobContext?.job_log||[]);current?.replaceWith(replacement.firstElementChild);bindJobLogActions($("[data-job-log-section]"),job);}
function showUpdateComposer(job,existing=null){const host=$("[data-update-composer]");if(!host)return;const entry=existing||{},today=todayIso(),activity=entry.work_type||"Initial inspection",statusValue=entry.status||"completed";host._entry=entry;host.hidden=false;host.innerHTML=`<div class="composer-heading"><strong>${existing?"Edit job-log update":"Add job-log update"}</strong><small>${existing?"Changes keep a revision history":"This also feeds Snapshot"}</small></div><div class="composer-grid"><label>Date<input type="date" data-update-field="work_date" value="${attr(String(entry.work_date||today).slice(0,10))}"></label><label>Activity<select data-update-field="work_type">${["Initial inspection","Demo","Monitor","Equipment placed","Equipment pickup","Contents","Recon","Final inspection","Other"].map(value=>`<option ${value===activity?"selected":""}>${value}</option>`).join("")}</select></label><label>Status<select data-update-field="status">${["completed","scheduled","rescheduled","cancelled","skipped","needs_review"].map(value=>`<option value="${value}" ${value===statusValue?"selected":""}>${value.replaceAll("_"," ")}</option>`).join("")}</select></label><label>Crew<input data-update-field="technicians" value="${attr(entry.technicians||"")}" placeholder="Technician or crew"></label><label class="wide">Work completed / next step<textarea rows="3" data-update-field="note" placeholder="What happened, what was completed, and what comes next">${esc(entry.note||"")}</textarea></label></div><div class="composer-actions"><button class="primary-action" data-save-update>${existing?"Save changes":"Save update"}</button><button class="quiet-button" data-cancel-update>Cancel</button><span data-update-status></span></div>`;host.scrollIntoView({behavior:"smooth",block:"nearest"});$("[data-cancel-update]",host).addEventListener("click",()=>{host.hidden=true;host._entry=null;});$("[data-save-update]",host).addEventListener("click",()=>saveUpdate(job,host));}
async function saveUpdate(job,host){const button=$("[data-save-update]",host),status=$("[data-update-status]",host),entry={...(host._entry||{}),source:host._entry?.source||"pc"};$$('[data-update-field]',host).forEach(field=>entry[field.dataset.updateField]=field.value);button.disabled=true;const prior=button.textContent;button.textContent="Saving…";const result=await transport("save_job_update",job.client,entry);if(!result?.ok){button.disabled=false;button.textContent=prior;status.textContent=result?.error||"Could not save";return;}if(!state.jobContext)state.jobContext={};state.jobContext.job_log=result.entries||[result.entry,...(state.jobContext.job_log||[])];replaceJobLog(job);host.hidden=true;toast(host._entry?.entry_id?"Job Log changes saved":"Job Log updated");}
async function runJobAction(action,button){const job={...state.selectedJob,...(state.jobContext||{})};const label=button.innerHTML;button.disabled=true;button.textContent="Opening…";try{const result=await transport("job_action",action,job);if(!result?.ok)throw new Error(result?.error||"Action unavailable");toast(action==="photo_report"?"CompanyCam report workspace opened":"Opened");}catch(error){toast(String(error instanceof Error?error.message:error));}finally{button.disabled=false;button.innerHTML=label;}}
async function copyValue(value,button){if(!value)return;let ok=false;if(window.pywebview?.api?.copy_text){const result=await transport("copy_text",value);ok=Boolean(result?.ok);}else{try{await navigator.clipboard.writeText(value);ok=true;}catch(_){}}toast(ok?"Copied":"Could not copy");button.closest("details")?.removeAttribute("open");}
function closeDrawer(){state.selectedJob=null;state.jobContext=null;$("[data-job-drawer]").hidden=true;$("[data-job-backdrop]").hidden=true;}
function toggleTools(){const menu=$("[data-tools-menu]"),willOpen=menu.hidden;menu.hidden=!willOpen;$("[data-tools-toggle]").setAttribute("aria-expanded",String(willOpen));}
function closeTools(){$("[data-tools-menu]").hidden=true;$("[data-tools-toggle]").setAttribute("aria-expanded","false");}
async function launchTool(tool,button){closeTools();const label=button.innerHTML,pendingWindow=!window.pywebview?.api?window.open("","_blank"):null;button.disabled=true;try{const mode=await resolveTransport();if(mode==="browser"){let route=state.toolRoutes[tool]||state.data?.tool_routes?.[tool];if(!route){const routes=await transport("tool_routes");state.toolRoutes=routes?.routes||{};route=state.toolRoutes[tool];}if(!route)throw new Error("That browser tool is not available yet.");if(pendingWindow){try{pendingWindow.opener=null;pendingWindow.location.replace(route);}catch(_){pendingWindow.location.href=route;}toast("Tool opened in a browser tab");}else location.assign(route);return;}pendingWindow?.close();const result=await transport("launch_tool",tool);if(!result?.ok)throw new Error(result?.error||"Tool could not open");toast("Tool opened in its own window");}catch(error){pendingWindow?.close();toast(String(error instanceof Error?error.message:error));}finally{button.disabled=false;button.innerHTML=label;}}
async function desktopAction(method,arg){if(window.pywebview?.api?.[method])return window.pywebview.api[method](arg);if(method==="open_url")window.open(arg,"_blank","noopener");else toast("Folder access is available in the desktop app.");}
function tick(){$("[data-clock]").textContent=new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});}
function setStatus(text,error=false){$("[data-status]").textContent=text;$("[data-status]").style.color=error?"var(--danger)":"";}
function toast(text){const el=$("[data-toast]");el.textContent=text;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,3500);}
function fmtDate(v){if(!v)return"—";const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(+d)?String(v):d.toLocaleDateString([],{month:"short",day:"numeric",year:"2-digit"});}
function fmtTime(v){const d=new Date(v);return Number.isNaN(+d)?"now":d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});}
function todayIso(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function initials(v){return String(v||"?").split(/[\s,()-]+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();}
function shortBoard(v){return String(v||"").replace("WORK IN PROGRESS","Work in progress").replace("ESTIMATING","Estimating").replace("CONTENTS","Contents");}
function shortDivision(v){return v==="CONTENTS"?"Contents":v==="RECON"?"Recon":"EMS";}
